# Sops configuration for Fracture
#
# Setup:
#   1. Generate an age key:  age-keygen -o ~/.config/sops/age/keys.txt
#   2. Add the public key below (replace the placeholder)
#   3. Populate the secret files under secrets/
#   4. Encrypt each file:    sops --encrypt --in-place <file>
#
# For system-level access, copy the age key to /etc/sops/age/keys.txt

keys:
  - &user age12md8stgfw6cuyqr8r7lqesfs4yjua06ud2p8d4x5ftqx32a3eeus26v7rn

creation_rules:
  - path_regex: secrets/auth/.*\.yaml$
    key_groups:
      - age:
          - *user
  - path_regex: secrets/ssh/.*\.yaml$
    key_groups:
      - age:
          - *user
  - path_regex: secrets/api/.*\.yaml$
    key_groups:
      - age:
          - *user
